#!/bin/sh
# (C) 1999-2018 Sebastien Godard (sysstat <at> orange.fr)
#
# Adapted by Bergware International for use in unRAID OS
# Moved /usr/lib64/sa/sa1 --> /usr/local/emhttp/plugins/dynamix.system.stats/scripts/sa1
#

HISTORY=0
SADC_OPTIONS=""
SA_DIR=/var/sa
SYSCONFIG_DIR=/usr/lib64/sa
umask 0022

[[ -r $SYSCONFIG_DIR/sysstat ]] && . $SYSCONFIG_DIR/sysstat
[[ -d $SA_DIR ]] || SA_DIR=/var/sa
[[ $HISTORY -gt 28 ]] && SADC_OPTIONS="$SADC_OPTIONS -D"

ENDIR=/usr/lib64/sa
cd $ENDIR
[[ $1 == --boot ]] && shift && BOOT=y || BOOT=n
if [[ $# == 0 && $BOOT == n ]]; then
  # Note: Stats are written at the end of previous file *and* at the
  # beginning of the new one (when there is a file rotation) only if
  # outfile has been specified as '-' on the command line...
  exec $ENDIR/sadc -F -L $SADC_OPTIONS 1 1 $SA_DIR
else
  exec $ENDIR/sadc -F -L $SADC_OPTIONS $* $SA_DIR
fi
