#!/bin/bash
plugin=dynamix.cache.dirs
cfg="/boot/config/plugins/$plugin/$plugin.cfg"
if [ ! -e $cfg ]; then
  cfg="/usr/local/emhttp/plugins/$plugin/default.cfg"
fi
conf=/etc/cache_dirs.conf

enable=$(grep "^service=" $cfg|cut -d'"' -f2)

echo "cache_dirs event $(basename "$0"): enable=$enable" | logger "-tcache_dirs"

if [[ $enable == 1 ]]; then
  if [[ ! -f $conf ]]; then
    grep '^options=' $cfg|cut -d'"' -f2-|sed 's:"$::'|tr -d "\n" > $conf
    echo "cache_dirs event $(basename "$0"): no $conf, generated new" | logger "-tcache_dirs"
  fi
  /usr/local/emhttp/plugins/$plugin/scripts/rc.cachedirs start >/dev/null
fi
