#!/bin/bash
plugin="dynamix.cache.dirs"
cfg="/boot/config/plugins/$plugin/$plugin.cfg"
if [ ! -e $cfg ]; then
  cfg="/usr/local/emhttp/plugins/$plugin/default.cfg"
fi
conf="/etc/cache_dirs.conf"
enable=$(grep "^service=" $cfg|cut -d'"' -f2)
if [ "$enable" == "1" ]; then
  if [ ! -f $conf ]; then
    grep "^options=" $cfg|cut -d'"' -f2-|sed 's:"$::'|tr -d "\n" > $conf
  fi
  /usr/local/emhttp/plugins/$plugin/scripts/rc.cachedirs start >/dev/null
fi
