#!/bin/bash
/usr/local/emhttp/plugins/dynamix.file.integrity/scripts/rc.watcher stop >/dev/null

pids=$(ps -eo pid,comm|awk '$2=="bunker" {print $1}')
for pid in $pids; do
  cpid=$(pgrep -P $pid 2>/dev/null)
  [[ -n $cpid ]] && kill $cpid 2>/dev/null
  kill $pid 2>/dev/null
done
